
server:
  port: 8080
spring:
  application:
    name: es-demo
  elasticsearch:
    rest:
      #username: user
      #password: 123456
      uris: http://10.10.66.58:9200
    #============================================================================
    # Elasticsearch-核心配置
    #============================================================================
    # http连接超时时间
    connectTimeout: 1000
    # socket连接超时时间
    socketTimeout: 30000
    # 获取连接的超时时间
    connectionRequestTimeout: 500
    # 最大连接数
    maxConnTotal: 100
    # 最大路由连接数
    maxConnPerRoute: 100
    # 任务最长可执行时间 (单位:小时)
    executeTimeout: 8
    # 用户名
    username: admin
    # 密码
    password: 123456