spring:
  application:
    name: eureka-consumer
server:
  port: 8098

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP地址
  client:
    service-url:
      #注册中心服务端web地址为http://localhost:8086/；客户端需加上/eureka/才能访问
      defaultZone: http://localhost:8086/eureka/